# Site settings
title:          djoernal
description:    "drepram's journal"
baseurl:        ""
url:            "https://djoernal.drepram.com"

# Google Analytics
google_analytics: UA—122570966-9

# Author
author:
  name:         Andre Christoga Pramaditya
  url:          https://drepram.com
  email:        caxvis@gmail.com

# Build settings
markdown:       kramdown
include:
  - _pages

# Assets
sass:
  sass_dir:     _sass
  style:        compressed

# Gems
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap
  # - jemoji #Uncomment this to allow emoji in your post

# Permalinks
permalink:      /:title.html
paginate:       5
